### ISSUE TITLE
Docker / BrowserSync / Mix

### ISSUE THREAD

**Issue by CordMarston** [AnowarCST/laravel-vue-crud-starter#27]
I've got this all setup and working flawlessly besides the "browserSync" no matter what I try I can not get it to load.

Is there a simple guide or tutorial on how to get it to work with this package?

**Comment by AnowarCST** [comment]
Sorry for replying late. Is it possible to explain with some details?

**Comment by iamraju** [comment]
Hi @AnowarCST 
I am also trying to use this and found quite good. I am not that good with docker but I wanted to use it via docker for some reason this time. I am able to run the application without any issues but the problem that I found is;

First of all, I found no `NodeJs` and `npm` are installed in the docker image/container or is it not necessary to install in the docker and my laptop's `npm` works fine ? Secondly I did not find a way to watch the changes that I made for Vue files. Can you help me (us) to configure `nodejs` and watcher run in the docker so that I can just make changes in the files and refresh the browser please ?

**Comment by AnowarCST** [comment]
@iamraju Hi thanks for using this.

If you want to write some codes in vuejs you need to install nodejs and npm in your machine. Because as a template I didn't include it here. To check your changes, run `npm install` and `npm run watch` in your project directory.
